Repository Year-3-Assignments/school-api, pull requests merged in 2021-08, with the labels that each got.

#16 Student management CRUD - Raveena
  src/controller/controller.enums.js
  src/controller/student.controller.js
  src/model/Student.js
  src/routes.js
Labels: api, database-model, enhancement

#24 Student Changes from Develop to master
  src/controller/controller.enums.js
  src/controller/student.controller.js
  src/model/Student.js
  src/routes.js
Labels: enhancement

#25 Member/rusiru
  azure-schoo-api.yaml
  config.js
  package-lock.json
  package.json
  server.js
  src/controller/exam.controller.js
  src/controller/question.controller.js
  src/model/Exam.js
  src/model/Question.js
  src/routes.js
Labels: database-model, api

#26 Student Management backend functions done
  package-lock.json
  src/controller/student.controller.js
Labels: enhancement, database-model, api

#27 Member/rusiru
  src/controller/user.controller.js
  src/routes.js
Labels: api
